/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "json_serializer.h"
#include <stdio.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void demo_json_serialization(void)
{
    char json_buffer[512];
    size_t json_length;

    DataPoint dp = {
        .timestamp = "1970-01-01 00:00",
        .meter_datetime = "1970-01-01 00:00",
        .total_m3 = 107.752f,
        .status = "OK"
    };

    DeviceReading device = {
        .media = "water",
        .meter = "waterstarm",
        .deviceId = "stromleser_50898527",
        .unit = "m3",
        .data = &dp,
        .data_count = 1
    };

    Payload payload = {
        .meta = {
            .gatewayId = "gateway_1234",
            .date = "1970-01-01",
            .deviceType = "stromleser",
            .interval_minutes = 15,
            .total_readings = 1
        },
        .values = {
            .device_count = 1,
            .readings = &device
        }
    };

    JsonStatus status = serialize_to_json(
        &payload,
        json_buffer,
        sizeof(json_buffer),
        &json_length
    );

    if (status == JSON_OK) {
        printf("Generated JSON (%lu bytes):\n%s\n",
               (unsigned long)json_length,
               json_buffer);
    } else {
        printf("JSON serialization failed: %d\n", status);
    }
}


int main(void)
{
	demo_json_serialization();
    /* Loop forever */
	for(;;);
}
